#!/usr/bin/python

# To solve this problem, make the './run' executable handle any
# appropriate command line arguments and stdin and output the
# solution to stdout.

# Water   0.30
# Wood    0.15
# Coal    0.10
# Iron    0.05
# Stone   0.10
# Obsidian    0.15
# Copper  0.05
# Gold    0.03
# Silver  0.07
import math

weights = .3, .15, .1, .05, .1, .15, .05, .03, .07

scores = []

while 1:
    try:
        s = raw_input()
    except EOFError:
        break

    score = sum(w * math.log(float(val)) for w, val in zip(weights, s.split()))
    scores.append(score)

for i, score in sorted(enumerate(scores), key=lambda p:-p[1]):
    print i


